apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
         - matchExpressions:
             - key: class
               operator: In
               values:
                - first
  containers:
  - name: container-affinity
    image: nginx
