apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
         - matchExpressions:
             - key: class
               operator: NotIn
               values:
                - first
  containers:
  - name: container-affinity-2
    image: nginx
