---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ci
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 83
    targetPort: 80
  selector:
    app: nginx
