apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod-1
  labels:
    app: wordpress
spec:
  containers:
      - image: gxg513/wordpress
        name: wordpress-container
        ports:
        - containerPort: 80
  imagePullSecrets:
  - name: regcred
