kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging" 
spec:
  tls:
    - hosts:
        - "www.grafana.com"
      secretName: ingress-demo-tls
  rules:
  - host: "www.grafana.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-grafana
            port:
              number: 80
