apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: test-ns
spec:
  encryptedData:
    password: AgAx+fweDCZU0zFYeeR59jYJze1l8P2cf7TsZ7GbwraNP5jInmIRqTEQ0BVLRvkVIgqgIrZIIB5lkQQvEbgDT4/oVHlz4kTe6C+YOyrPZjL6WcMu+5gdgyIKN3hsUflN4Ff1YJXuV8TA8TMceDP4wEJZVy1yrytb461Pm2LJXFlhWRkRdr9mVTSPvMWaMuQz7exe0+2FmbSEbl42fNFM1vhB4SPKeJvgspMSkaJg5z62AUtB9ngZnCZ4u1/1KHoOju0vWOaBvaRtkbvTd07Gd/F3QiM+DVfLZbQ6yS4Hc45OdpOYQMo722NJy/HUpSwPfwR9/eHKOKeWq5PpnTNkCSx8PnLKYYH6/mcPc/W7M9k+hHhdq3+L3jmBleI8BspAl7TNplueHRYV7/Jxz3T8I9fgkXyuP9a91AW2EPm6MALNSplpNa6H0hcmbLeIhKReg7wMGHz9nxle9HXqQW67NanQf6Z7ugA+yuB43RmxW4nxgEIjI18UvRr7X4lUCB7xX6SE6xjShleLVaCg2IktI0JJMOwTf8D7UDYoKotgjfBOtQ89SzpoN7PRbDcgdk1W7g56M7MhaZJ38vUNYMsk30jIx/RA3eKvCnFMxOpmXP7yk7E5ui4O8AuYrumoEZzH34oXni1KZJbG874ZuFB93OyEeLgmP04guVJZbP0JYFaXmTehpQ4U1j1VZRIKtE8Hv8ywN8l6LhskXg==
    username: AgDDur29TEwCyl5d0pCsaM65MWR/JjK3MPyLcj40O+e1XF+S+WGj0iZvKR8x4x4/QamDT44Uw4OeO52/1XHiMJMeh+PltvCld/1stG4HWdZI0/rIptWwvveFhBLZB6wKcF0cLHNNvDxhonU4QGX75pZJ/SkzwTxWR3Ar4EA8fnwmd+/bsOf9dOvnzSdDOdAjaVkK+lQisnA6zxa/jvpLl/Kx6ydWUFwmX/vaaH/caU23bjPI2kBNSrAePRyvskDN6ggszZzzUsOvFw1AO185lFGd/hiHL2w5pO+aMhx6kv87FVNw9Zj0yBcntFDxqCkYkZ8snL0ZCItqla1ZgvE96vnRq+Iy0fD3aGcKV5mXoF9ewkNeshFEA8Q2dNjSVbeinz9I++2xtX7QMOxgj1Bls6Lld0daGE2/KsLPVw/R8yKyaAx/2fnYhKf6yoI8xV250CJ3H1ACmfGgsZbl+BbFnLagyOIrm/nlD0GYIAQ1+gONYWLdViLBfkipr03mKI/Exq9+r8qDen7DSTqePd5yunKTQKIsq83wRoSQu+tFAZHU/cJAJok1CCg1GAKZUTo2NSGdvu8KEewPo+SQ4ykriwuUnjyVeT1dGV9elUe3rm+LReoI2/UJKplVmS+iXv90S/5qA0o/CfxtUWzIjelslwhvEhmnnKENI6x+5GF0ls6S1JkI3Cizsp0r2T+8UHq22kZAbBnKzhCechVVKIRsYA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: test-ns

