apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler-2
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - "3"
  containers:
  - name: pv-recycler-2
    image: "nginx"
  #   volumeMounts:
  #    - mountPath: "/folder"
  #      name: myvol-2
  # volumes:
  #   - name: myvol-2
  #     persistentVolumeClaim: 
  #       claimName: task-pv-claim-2
