apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/plm/data"
