---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: NodePort
  ports:
  - name: http
    port: 82  # service port
    protocol: TCP
    targetPort: 80 # POD
    nodePort: 30163 # external service port which is mapped to the node 
  selector:
    app: nginx
