apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000 
    fsGroup: 2000
  volumes:
  - name: sec-vol
    emptyDir: {}
  containers:
  - name: mybusyboxcontainer
    image: busybox
    command: [ "sh", "-c" , "sleep 1h"]
    volumeMounts:
    - name: sec-vol
      mountPath: /data/demo
