apiVersion: batch/v1
kind: Job
metadata:
  name: postinstall-hook-job
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    spec: 
      containers:
      - name: pre-install
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh','-c','echo post install job pod; sleep 10']
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1
