apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "updated simple configmap"
  zone: {{ quote .Values.infra.zone }}
  zone2: {{ upper .Values.infra.planet }}
