---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: webapp-sql
    tier: frontend
spec:
  selector:
    matchLabels:
      app: webapp-sql
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: frontend
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: webapp1
        image: gxg513/database-website
        imagePullPolicy: Always
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: secret-name
                key: user
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: secret-name
                key: db
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-name
                key: user_pass
        ports:
         - containerPort: 80
        volumeMounts:
         - name: task-pv-storage
           mountPath:  "/var/www/html"
