---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: webapp-sql
    tier: frontend
spec:
  selector:
    matchLabels:
      app: webapp-sql
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: frontend
    spec:
      containers:
      - name: webapp1
        image: gxg513/website
        imagePullPolicy: Always
        ports:
         - containerPort: 80
        volumeMounts:
         - name: nginx-index-file
           mountPath: /var/lib/html/
      volumes:
        - name: nginx-index-file
          configMap:
            name: myconfigmap
