kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "www.grafana.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-grafana
            port:
              number: 80
